export const IHCM_MESSAGE = {
    TOGGLE_LIST_GROUP: "TOGGLE_LIST_GROUP",
    OPEN_BOX_CHAT: "OPEN_BOX_CHAT",
    CLOSE_BOX_CHAT: "CLOSE_BOX_CHAT",
    OPEN_VIDEO_CALL: "OPEN_VIDEO_CALL",
    CLOSE_VIDEO_CALL: "CLOSE_VIDEO_CALL"
}