//08/01/2021 : vinhtq: thêm TYPE_VIDEO_CALL,TYPE_NOTIFICATION
export enum PushStreamTypes {
    NEW_MESSENGER = 'NEW_MESSENGER',
    UPDATED_STATUS_USER = 'UPDATED_STATUS_USER',
    NEW_USER_CHAT = 'NEW_USER_CHAT',
    TYPE_DELETED_MESSENGER = 'TYPE_DELETED_MESSENGER',
    TYPE_VIDEO_CALL = 'VIDEO_CALL',
    TYPE_NOTIFICATION = 'NOTIFICATION',
    UPDATE_MESSENGER = "UPDATE_MESSENGER",
    UPDATE_ONLINE_OFFLINE = "UPDATE_ONLINE_OFFLINE",
    CREATE_CHAT_ROOM = "CREATE_CHAT_ROOM"
}