var env: any = null;
try {
  env = require("react-native-config");
} catch {}

console.log('test_app-config_env: ', env)
const IS_WEB = process.env?.REACT_APP_IP_ADDRESS_URL !== undefined;
const REACT_APP_IP_ADDRESS_URL = IS_WEB
  ? process.env.REACT_APP_IP_ADDRESS_URL
  : env?.Config?.REACT_APP_IP_ADDRESS_URL;

const REACT_APP_PUSH_STREAM_PROTOCOL = IS_WEB
  ? process.env.REACT_APP_PUSH_STREAM_PROTOCOL
  : env?.Config?.REACT_APP_PUSH_STREAM_PROTOCOL;

const REACT_APP_PUSH_STREAM_URL = IS_WEB
  ? process.env.REACT_APP_PUSH_STREAM_URL
  : env?.Config?.REACT_APP_PUSH_STREAM_URL;

const SERVER_FILE = IS_WEB
  ? process.env.REACT_APP_IP_ADDRESS_FILE
  : env?.Config?.REACT_APP_IP_ADDRESS_FILE;
  
const REACT_APP_DOMAIN_IHCM = IS_WEB
  ? process.env.REACT_APP_DOMAIN_IHCM
  : env?.Config?.REACT_APP_DOMAIN_IHCM;

const APP_CONFIGS = {
  DEFAULT_NUMBER_PAGE: 1,
  ITEM_PER_PAGE: 20,
  CHAT_ITEM_PER_PAGE: 20,
  URL_API: `${REACT_APP_IP_ADDRESS_URL}`,
  PUSH_STREAM_PROTOCOL: `${REACT_APP_PUSH_STREAM_PROTOCOL}`,
  URL_PUSH_STREAM: REACT_APP_PUSH_STREAM_URL,
  SERVER_FILE: SERVER_FILE,
  REACT_APP_DOMAIN_IHCM: REACT_APP_DOMAIN_IHCM,
};

export { APP_CONFIGS };
